### PR TITLE
Add c-ts-mode and c++-ts-mode to supported modes

### PR DESCRIPTION
**Pull request by bastianbeischer**

### CODE REVIEW

**Comment by yyoncho** [comment]
FTR it will be better to switch to activate-on like in this PR - https://github.com/emacs-lsp/lsp-mode/pull/3873 . Willing to do that change?

**Comment by bastianbeischer** [comment]
Sure!

**Comment by bastianbeischer** [comment]
@yyoncho ping :)

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
Thank you

**Pull request merged**
